version: "3.8"

services:
  service-a:
    build:
      context: ./service-a
      dockerfile: DockerFile
    ports:
      - "8000:8000"
    env_file:
      - ./service-a/.env
    depends_on:
      - chromadb
      - neo4j

  service-b:
    build:
      context: ./service-b
      dockerfile: DockerFile
    ports:
      - "8001:8000"
    env_file:
      - ./service-b/.env
    depends_on:
      - chromadb
      - neo4j

  chromadb:
    image: chromadb/chroma:latest
    ports:
      - "8002:8000"
    volumes:
      - chroma_data:/chroma/.chroma/index
    environment:
      - IS_PERSISTENT=TRUE

  neo4j:
    image: neo4j:5.18
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/password
    volumes:
      - neo4j_data:/data

volumes:
  chroma_data:
  neo4j_data: